### ISSUE TITLE
第一周-学习HTML

### ISSUE THREAD

**Issue by ElvisNam** [FE-boom/IFE-task#1]
##### 1. 学习任务：

- 掌握前后端工作方式及专有名词含义：[Web相关名词通俗解释](https://www.zhihu.com/question/22689579)

- 掌握HTML基础：[MDN HTML入门](https://developer.mozilla.org/zh-CN/docs/Web/HTML)

- 学习慕课网内HTML部分（第1-5章）：[慕课HTML+CSS基础教程视频](http://www.imooc.com/learn/9)

- 了解HTML的标签含义：[W3School HTML教程](http://www.w3school.com.cn/html/index.asp)（此教程为参考教程，类似工具字典，适合对标签、属性的临时性查阅）

##### 2. 任务目的：

- 了解HTML的定义、概念、发展简史

- 掌握常用HTML标签的含义、用法

- 能够基于设计稿来合理规划HTML文档结构

- 理解语义化，合理地使用HTML标签来构建页面

##### 3. 任务描述：

- 参考[示例图（点击查看）](https://github.com/FE-boom/IFE-task/blob/master/Task1/images/task_1_1_1.jpg)，完成一个HTML页面代码编写（不写CSS，不需要关注样式，只关注文档结构）

##### 4. 注意事项：

- 只需要完成HTML的编写，不需要写CSS。

- 尽可能多地尝试更多的标签，尽可能地令标签语义化。

- 若无特殊声明，今后的代码仓库为[IFE-task](https://github.com/FE-boom/IFE-task)。每一个任务为一个独立的文件夹，本次任务请提交至：[IFE-task/Task1](https://github.com/FE-boom/IFE-task/tree/master/Task1)。（请注意，在今后的每次任务中，请先创建一个分支，并以自己的名字为名新建一个文件夹，将自己的文件保存在该的文件夹内。现阶段，请不要直接对主干master进行操作，以免造成不可挽回的损失）

- 在完成任务过程中，不应该将代码文件留到最后完成后才提交，而是应以时间段的方式进行提交，令其记录你的历史操作，让管理员更好的给出建议。

- 在编写代码中，应注意代码格式规范。时刻谨记**代码是给人看的，而不是给机器看的**。

##### 5. 思考：

- 在HTML学习过程中，请注重**标签语义化**的理解，同时在编写过程中也应当建立**标签语义化**的思维。

- 自行搜索并了解HTML5、HTML4.01、XHTML之间的区别。

- 自行搜索并了解<!DOCTYPE>的含义。（以上三者均为面试重点）

- 自行搜索并掌握内联元素、块级元素的区别。

##### 6. 合作要求：

- 明确题目要求，独立完成任务。

- 每个人至少查看一个组员的代码，与自己的代码进行对比，看两者代码在相同的内容段中是否用到不同的标签，并思考谁的更符合语义化。**同时在自己查看的组员下提交评论建议**

- 每个人的代码管理员都会帮忙review并给出相应建议。

***
预期完成时间：11月19日（周五）
最迟完成时间：11月21日（周日）
完成后请在下方回复。

**Comment by Liu-yan** [comment]
已完成

**Comment by sliop** [comment]
已完成

**Comment by HermesZ** [comment]
https://github.com/HermesZ/learngit/blob/master/test.html

**Comment by sliop** [comment]
https://github.com/sliop/learngit/blob/dev/task1/task_1_1_1.html
