### ISSUE TITLE
第二周-学习CSS

### ISSUE THREAD

**Issue by ElvisNam** [FE-boom/IFE-task#2]
##### 1. 学习任务：

- 掌握CSS基础：[MDN CSS入门教程](https://developer.mozilla.org/zh-CN/docs/Web/Guide/CSS/Getting_started)

- 学习慕课网内CSS部分（6-16章）：[慕课HTML+CSS基础教程视频](http://www.imooc.com/learn/9)

- 了解CSS各属性及其值的含义与用法：[W3School CSS教程](http://www.w3school.com.cn/css/index.asp)

##### 2. 任务目的：

- 针对设计稿样式进行合理的HTML架构，包括以下但不限于：

  - 掌握常用HTML标签的含义、用法；
 
  - 能够基于设计稿来合理规划HTML文档结构

  - 理解语义化，合理地使用HTML标签来构建页面

- 掌握基本的CSS编码，包括以下但不限于：

  - 了解CSS的定义、概念、发展简史
  
  - 掌握CSS选择器的含义和用法

  - 实践并掌握CSS的**颜色、字体、背景、边框、盒模型、简单布局等样式**的定义方式     

##### 3. 任务描述：

- 基于“第一周-学习HTML”的代码，参考[示例图（点击查看）](https://github.com/FE-boom/IFE-task/blob/master/Task2/images/task_1_2_1.jpg)，在该任务的代码基础上增加CSS样式代码的编写

##### 4.注意事项：

- 只需要完成HTML，CSS代码编写，不需要写JavaScript

- 尽可能多地尝试不同的、更多的样式设定来实践各种CSS属性

- HTML 及 CSS 代码结构清晰、规范

##### 5.思考：

- 了解CSS2.1及CSS3之间的关系、区别。

- 掌握CSS嵌入式、内联式、外联式的写法方式、优缺点、权限优先级，**并自行判断采用最佳方式在本次CSS代码编写中**。

- 掌握id属性、class属性的含义、区别、标签中使用时的选择方式。

- 掌握CSS选择器的类别、使用方式、权限优先级的计算方式。

- 深入理解CSS盒模型（标准盒模型、IE盒模型）

##### 6. 合作要求：

- 明确题目要求，独立完成任务。

- 每个人至少查看一个组员的代码（不可与前期任务查看的重复），与自己的代码进行对比，提交评论建议。
***
预期完成时间：11月21日（周一）
最迟完成时间：11月25日（周五）

**Comment by DreamHyu** [comment]
完成。

**Comment by ElvisNam** [comment]
@DreamHyu 除logo图片外，其余应用CSS属性实现，而不是过渡切图实现，否则会带来不必要的流量开销，导致性能过慢。请思考并重新修改。

**Comment by songyuanxianha** [comment]
完成

**Comment by Liu-yan** [comment]
完成

**Comment by sliop** [comment]
https://github.com/sliop/learngit/tree/dev/task1

**Comment by bauhiniaA** [comment]
已提一次

**Comment by HermesZ** [comment]
https://github.com/HermesZ/learngit
