### ISSUE TITLE
第二周-学习CSS布局

### ISSUE THREAD

**Issue by ElvisNam** [FE-boom/IFE-task#3]
##### 1. 学习任务：

- 掌握CSS position属性的基本知识：[MDN position](https://developer.mozilla.org/zh-CN/docs/Web/CSS/position)

- 掌握CSS float属性的基本知识：[MDN float](https://developer.mozilla.org/en-US/docs/Web/CSS/float)

- 通过具体的例子学习position属性：[Learn CSS Positioning in Ten Steps](http://www.barelyfitz.com/screencast/html-training/css/positioning/)

- 掌握CSS布局：[CSS布局](http://zh.learnlayout.com/)

- 清除浮动是什么，如何有效的清除浮动：[清除浮动clearfix](http://zh.learnlayout.com/clearfix.html)

- 清除浮动黑科技完整解读：[What methods of ‘clearfix’ can I use?](http://stackoverflow.com/questions/211383/what-methods-of-clearfix-can-i-use)

- 慕课网布局视频参考：[如何用CSS进行网页布局](http://www.imooc.com/learn/57)、[网页布局基础](http://www.imooc.com/learn/95)

##### 2. 任务目的：

- 掌握HTML/CSS布局的概念

- 掌握盒模型的概念

- 掌握position与float的概念以及在布局时的用法

- 掌握一列布局、二列布局、三列布局；左右侧栏宽度固定，中间内容部分固定的响应式三列布局（见练习）

- 在上一条的实现基础上，如何实现**响应式的符合HTML语义化的布局**

##### 3. 任务描述：

- 使用HTML和CSS按照[示例图（点击查看）](https://github.com/FE-boom/IFE-task/blob/master/Task3/images/task_1_3_1.png)实现三栏式布局

- 左右两栏宽度固定，中间一栏根据父元素宽度填充满，最外面的框应理解为浏览器。背景色为 #eee 区域的高度取决于三个子元素中最高的高度。

##### 4. 注意事项：

- 效果图能正确还原。

- 尝试 position 和 float 的效果，思考它们的异同和应用场景。

- 注意测试不同情况（改变浏览器大小），尤其是极端情况下的效果。

- 调节浏览器宽度，固定宽度和自适应宽度的效果始终符合预期。

- 改变中间一栏的内容长度，以确保在中间一栏较高和右边一栏较高时，父元素的高度始终为子元素中最高的高度。

##### 5. 思考：

- position各值的含义、特点。

- 何为自适应式（响应式）布局？

##### 6. 合作要求：

- 明确题目要求，独立完成任务。

- 每个人至少查看一个组员的代码（不可与前期任务查看的重复），与自己的代码进行对比，提交评论建议。

***
最迟完成时间：11月25日（周五）

**Comment by Liu-yan** [comment]
完成

**Comment by DreamHyu** [comment]
完成

**Comment by songyuanxianha** [comment]
完成
