### ISSUE TITLE
第二周-CSS定位和浮动

### ISSUE THREAD

**Issue by ElvisNam** [FE-boom/IFE-task#4]
##### 1. 学习任务：

- 大漠定位教程：[HTML和CSS高级指南之二——定位详解](http://www.w3cplus.com/css/advanced-html-css-lesson2-detailed-css-positioning.html)

- 完整讨论了不同情况下的居中方案，建议自己思考之后再看答案：[Centering in CSS: A Complete Guide](https://css-tricks.com/centering-css-complete-guide/)

##### 2. 任务目标：

- 针对始终没搞懂定位问题，每次都靠运气实现定位的人

- 实践HTML/CSS布局方式

- 深入理解position、float等CSS属性

##### 3. 任务描述：

- 实现如[示例图（点击查看）](https://github.com/FE-boom/IFE-task/blob/master/Task4/images/task_1_4_1.png)的效果

- 灰色元素水平垂直居中，有两个四分之一圆位于左上角和右下角（提示：圆形参考属性：border-radius）

##### 4. 注意事项：

- 思考不同情况下（如灰色高度是根据内容动态变化的）水平垂直居中的解决方案。

- 动手试一试各种情况的组合，父元素和子元素分别取不同的 position 值。思考 position 属性各种取值的真正含义，尤其是 absolute 究竟是相对谁而言的。

- 注意测试不同情况，尤其是极端情况下的效果。

- 调节浏览器宽度，灰色元素始终水平居中。

- 调节浏览器高度，灰色元素始终垂直居中。

- 调节浏览器高度和宽度，黄色扇形的定位始终准确。

- 其他效果图中给出的标识均被正确地实现，错一项扣一分。

##### 5. 思考：

- 学到现在，你明白反复强调CSS布局和定位的意义在哪了吗？学习中你遇到了多少坑，你总结了解决方法了吗？

- 总结：元素水平居中、垂直居中的方法（元素宽高固定的情况、元素宽高不固定的情况）

##### 6. 合作要求：

- 明确题目要求，独立完成任务。

- 每个人至少查看一个组员的代码（不可与前期任务查看的重复），与自己的代码进行对比，提交评论建议。

***
最迟完成时间：11月25日（周五）

**Comment by Liu-yan** [comment]
完成

**Comment by DreamHyu** [comment]
完成

**Comment by songyuanxianha** [comment]
完成

**Comment by bauhiniaA** [comment]
完成

**Comment by sliop** [comment]
https://github.com/sliop/learngit/tree/dev/task_1_4_1
