### ISSUE TITLE
第三周-HTML与CSS页面还原（1）

### ISSUE THREAD

**Issue by ElvisNam** [FE-boom/IFE-task#5]
##### 1. 任务目的：

- 针对设计稿样式进行合理的HTML架构，包括以下但不限于：

  - 掌握常用HTML标签的含义、用法

  - 能够基于设计稿来合理规划HTML文档结构

  - 理解语义化，合理地使用HTML标签来构建页面

- 掌握基本的CSS编码，包括以下但不限于：   

  - 了解CSS的定义、概念、发展简史

  - 掌握CSS选择器的含义和用法

  - 实践并掌握CSS的颜色、字体、背景、边框、盒模型、简单布局等样式的定义方式

##### 2. 任务描述：

- 基于“学习HTML”的代码，参考[示例图（点击查看）](https://github.com/FE-boom/IFE-task/blob/master/Task5/images/task_1_5_1.jpg)，在HTML代码的基础上增加CSS样式的编写

- 头部和底部的黑色区域始终是100%宽

- 页面右侧部分为固定宽度，左侧保持与浏览器窗口变化同步自适应变化

- 左侧的各个模块里面的内容宽度跟随左侧整体宽度同步自适应变化

- 10张图片需要永远都完整展现，所以会随着宽度变窄，从两行变成三行甚至更多，也有可能随着宽度变宽，变成一行

##### 3. 注意事项：

- 只需要完成HTML，CSS代码编写，不需要写JavaScript

- 尽可能多地尝试不同的、更多的样式设定来实践各种CSS属性

- HTML 及 CSS 代码结构清晰、规范

##### 4. 合作要求：

- 明确题目要求，独立完成任务。

- 每个人至少查看一个组员的代码（不可与前期任务查看的重复），与自己的代码进行对比，提交评论建议。

***
最迟完成时间：11月30日（周三）

**Comment by Liu-yan** [comment]
完成

**Comment by songyuanxianha** [comment]
完成
