### ISSUE TITLE
第三周-HTML与CSS页面还原（2）

### ISSUE THREAD

**Issue by ElvisNam** [FE-boom/IFE-task#6]
##### 1. 任务目的：

- 通过实现一个常见的技术产品官网，加深对于HTML，CSS的实战能力

- 学习掌握如何在没有标注的情况下实现设计稿到页面的精确转变

##### 2. 任务描述：

- 通过HTML与CSS实现设计稿[设计稿（点击查看）](https://github.com/FE-boom/IFE-task/blob/master/Task6/images/task_1_7_1.psd)，效果如[效果图（点击查看）](https://github.com/FE-boom/IFE-task/blob/master/Task6/images/task_1_7_2.jpg)。

- 设计稿是有一定宽度的，这个宽度为页面的最小宽度，也就是说，当浏览器窗口宽度小于设计稿宽度时，允许出现横向滚动条，页面内容宽度保持不变，但是当浏览器窗口宽度大于设计稿宽度时，页面部分内容的宽度应该保持和浏览器窗口宽度一致，具体哪些部分题目不做具体指明，看看大家的判断如何。

##### 3. 注意事项：

- 只需要完成HTML，CSS代码编写，不需要写JavaScript

- 在Chrome中完美实现与设计稿的各项字体、布局、内外边距等样式

- 尝试跨浏览器的兼容性（chrome、firefox、IE8、IE9、IE10）

##### 4. 合作要求：

- 明确题目要求，独立完成任务。

- 每个人至少查看一个组员的代码（不可与前期任务查看的重复），与自己的代码进行对比，提交评论建议。

***
最迟完成时间：12月2日（周五）

**Comment by songyuanxianha** [comment]
完成
