### ISSUE TITLE
第四周-学习JavaScript

### ISSUE THREAD

**Issue by ElvisNam** [FE-boom/IFE-task#8]
##### 1.学习任务：
- 学习DOM操作并熟记各类操作API：[参考书籍：《JavaScript DOM编程艺术》](https://book.douban.com/subject/6038371/)
- 学习JS基本概念、语法、数据类型、执行环境与作用域：[《JavaScript 高级程序设计》第1~5章](https://book.douban.com/subject/10546125/)
- 视频参考：[慕课网-JS入门篇](http://www.imooc.com/learn/36)、[慕课网-JS进阶篇](http://www.imooc.com/learn/10)

##### 2.任务目的：
- 理解JS组成结构：ECAMAScript、DOM、BOM
- 掌握JS DOM操作
- 掌握ECAMAScript语法、数据类型（基本数据类型、复杂数据类型）

##### 3,任务描述：
- 请参考[动态图（点击查看）](https://github.com/FE-boom/IFE-task/blob/master/Task7/images/img1.gif)，使用原生JS语法，完成各项要求。

##### 4.注意事项：
- 此阶段不可使用任何第三方库、框架，请学习原生JS语法、打好基础
- 请注意代码风格的整齐、优雅
- 代码中含有必要的注释

##### 5.思考：
- JS发展历史
- 编程初学者思考基本数据类型和复杂数据类型的区别（浅拷贝、深拷贝）

##### 6. 合作要求：
- 明确题目要求，独立完成任务。
- 每个人至少查看一个组员的代码（不可与前期任务查看的重复），与自己的代码进行对比，提交评论建议。

***
预期完成时间：2017年1月6日（周五）（期考已结束）
最迟完成时间：2017年1月13日（周五）（期考未结束）

**Comment by songyuanxianha** [comment]
完成

**Comment by DreamHyu** [comment]
完成的不好

**Comment by Liu-yan** [comment]
完成
