### ISSUE TITLE
第五～六周-JavaScript进阶学习

### ISSUE THREAD

**Issue by ElvisNam** [FE-boom/IFE-task#9]
##### 1.学习任务：
- 学习JavaScript高级语法知识：[参考书籍：《JavaScript 高级程序设计》](https://book.douban.com/subject/10546125/)

##### 2.任务目的：
- 完善并巩固JS基础知识
- 掌握引用数据类型及其原生功能API（Array、Date、Object等）
- 掌握函数基础知识（匿名函数、递归、闭包等）
- 掌握JS作用域知识
- 初步了解面向对象编程基础知识
- 掌握this及其相关知识

##### 3.任务描述：
- 本阶段任务较多，将不断发布更新至[Task8（点击查看）](https://github.com/FE-boom/IFE-task/tree/master/Task8)。完成作业提交时，将文件与相应任务图片名字保持一致提交（为方便查看，JS与CSS采用內联方式）

##### 4.注意事项：
- 此阶段不可使用任何第三方库、框架，请学习原生JS语法、打好基础
- 请注意代码风格的整齐、优雅
- 代码中含有必要的注释

##### 5. 合作要求：
- 明确题目要求，独立完成任务。
- 每个人至少查看一个组员的代码（不可与前期任务查看的重复），与自己的代码进行对比，提交评论建议。

***
最迟完成时间：2017年2月6日（周一）（期考未结束）

**Comment by songyuanxianha** [comment]
代码完成    该看的估计明天看完

**Comment by DreamHyu** [comment]
还在使劲看书！代码完了
